"""The iteration ledger (research-protocol §0.3: 「ループ回数は台帳(`ITER.md`)に累積し、
報告と帰無の多重性に必ず算入する」; item 3, old item 7: 「周回数の台帳」).

A ledger is a directory. Its record is `ITER.jsonl`: one line per trial,
append-only, each line carrying the sha256 of the previous line (a chain),
so a removed, reordered or edited line makes the ledger refuse to open. A
readable view `ITER.md` is regenerated after every append; it carries a
marker line, and a hand-written `ITER.md` (without the marker) is never
overwritten -- the ledger refuses instead.

    led = IterLedger(path)            # opens (and verifies) or starts empty
    led.add(design="d1", sr=0.1, note="...")   -> the entry
    led.count() / led.count(design="d1")
    deflated_sharpe_from_ledger(led, sr=, T=, skew=, kurtosis=, var_trials=)
        uses N = led.count() (every trial of the study counts towards the
        multiplicity); var_trials None -> the sample variance (ddof 1) of the
        trials' `sr` (every trial must then carry one).
"""
from __future__ import annotations

import hashlib
import json
import math
import os
from typing import Any, Optional

from ._args import as_float
from .errors import LedgerError, ValidationError
from .overfit import DSR, deflated_sharpe

RECORD = "ITER.jsonl"
VIEW = "ITER.md"
MARKER = "<!-- generated by bot.bt.validation.ledger from ITER.jsonl; edit nothing here -->"
_GENESIS = "0" * 64


def _canon(obj: Any) -> str:
    return json.dumps(obj, ensure_ascii=False, sort_keys=True, separators=(",", ":"), allow_nan=False)


class IterLedger:
    def __init__(self, path: str) -> None:
        if type(path) is not str or not path:
            raise LedgerError("the ledger path must be a non-empty str")
        self.path = path
        self._entries: list[dict] = []
        self._last = _GENESIS
        rec = os.path.join(path, RECORD)
        if os.path.exists(rec):
            with open(rec, "r", encoding="utf-8") as fh:
                for ln, line in enumerate(fh, 1):
                    if not line.strip():
                        raise LedgerError(f"{rec} line {ln} is empty: the ledger was edited")
                    try:
                        e = json.loads(line)
                    except json.JSONDecodeError as exc:
                        raise LedgerError(f"{rec} line {ln} is not JSON: {exc}") from None
                    body = {k: v for k, v in e.items() if k != "sha256"}
                    if body.get("n") != ln or body.get("prev") != self._last:
                        raise LedgerError(f"{rec} line {ln}: the chain is broken (n / prev do not follow)")
                    if hashlib.sha256(_canon(body).encode()).hexdigest() != e.get("sha256"):
                        raise LedgerError(f"{rec} line {ln}: its hash does not match its content")
                    self._entries.append(e)
                    self._last = e["sha256"]
        view = os.path.join(path, VIEW)
        if os.path.exists(view):
            with open(view, "r", encoding="utf-8") as fh:
                if MARKER not in fh.read():
                    raise LedgerError(f"{view} exists and was not written by this ledger; refusing to take it over")

    def entries(self) -> list[dict]:
        return [dict(e) for e in self._entries]

    def count(self, design: Optional[str] = None) -> int:
        return sum(1 for e in self._entries if design is None or e["design"] == design)

    def add(self, *, design: str, **fields: Any) -> dict:
        if type(design) is not str or not design:
            raise LedgerError("design must be a non-empty str (which design this trial belongs to)")
        for k in fields:
            if k in ("n", "prev", "sha256", "design"):
                raise LedgerError(f"field {k!r} is the ledger's own")
        body = {"n": len(self._entries) + 1, "prev": self._last, "design": design, **fields}
        try:
            text = _canon(body)
        except (TypeError, ValueError) as exc:
            raise LedgerError(f"a trial's fields must be plain finite JSON: {exc}") from None
        e = {**body, "sha256": hashlib.sha256(text.encode()).hexdigest()}
        os.makedirs(self.path, exist_ok=True)
        with open(os.path.join(self.path, RECORD), "a", encoding="utf-8") as fh:
            fh.write(_canon(e) + "\n")
            fh.flush()
            os.fsync(fh.fileno())
        self._entries.append(e)
        self._last = e["sha256"]
        self._write_view()
        return dict(e)

    def _write_view(self) -> None:
        lines = [MARKER, "", "# ITER(周回数の台帳)", "", f"試行の数: {len(self._entries)}", "",
                 "| # | 設計 | 欄 |", "|---|---|---|"]
        for e in self._entries:
            extra = {k: v for k, v in e.items() if k not in ("n", "prev", "sha256", "design")}
            lines.append(f"| {e['n']} | {e['design']} | `{_canon(extra)}` |")
        tmp = os.path.join(self.path, VIEW + ".tmp")
        with open(tmp, "w", encoding="utf-8") as fh:
            fh.write("\n".join(lines) + "\n")
        os.replace(tmp, os.path.join(self.path, VIEW))


def deflated_sharpe_from_ledger(ledger: IterLedger, *, sr: float, T: int, skew: float, kurtosis: float,
                                var_trials: Optional[float]) -> DSR:
    n = ledger.count()
    if n < 1:
        raise ValidationError("the ledger has no trial: register the trials before judging the best one")
    if var_trials is None:
        srs = []
        for e in ledger.entries():
            if "sr" not in e:
                raise ValidationError(f"trial {e['n']} has no 'sr'; give var_trials or record every trial's sr")
            srs.append(as_float(f"trial {e['n']} sr", e["sr"]))
        if len(srs) < 2:
            raise ValidationError("the variance of the trials' SR needs at least 2 trials")
        m = sum(srs) / len(srs)
        var_trials = sum((x - m) ** 2 for x in srs) / (len(srs) - 1)
    r = deflated_sharpe(sr=sr, T=T, skew=skew, kurtosis=kurtosis, n_trials=n, var_trials=var_trials)
    if not math.isfinite(r.dsr):
        raise ValidationError("the deflated Sharpe is not finite")
    return r
